// <auto-generated />
using System;
using ExcelDatabaseImportTool.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExcelDatabaseImportTool.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("ExcelDatabaseImportTool.Models.Configuration.DatabaseConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Database")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Server")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DatabaseConfigurations");
                });

            modelBuilder.Entity("ExcelDatabaseImportTool.Models.Configuration.FieldMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseFieldName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcelColumnName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ForeignKeyMappingId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ForeignKeyMappingId");

                    b.HasIndex("ImportConfigurationId");

                    b.ToTable("FieldMappings");
                });

            modelBuilder.Entity("ExcelDatabaseImportTool.Models.Configuration.ForeignKeyMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReferencedKeyField")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferencedLookupField")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferencedTable")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ForeignKeyMappings");
                });

            modelBuilder.Entity("ExcelDatabaseImportTool.Models.Configuration.ImportConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DatabaseConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasHeaderRow")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseConfigurationId");

                    b.ToTable("ImportConfigurations");
                });

            modelBuilder.Entity("ExcelDatabaseImportTool.Models.Domain.ImportLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorDetails")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExcelFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedRecords")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImportConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SuccessfulRecords")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImportConfigurationId");

                    b.ToTable("ImportLogs");
                });

            modelBuilder.Entity("ExcelDatabaseImportTool.Models.Configuration.FieldMapping", b =>
                {
                    b.HasOne("ExcelDatabaseImportTool.Models.Configuration.ForeignKeyMapping", "ForeignKeyMapping")
                        .WithMany("FieldMappings")
                        .HasForeignKey("ForeignKeyMappingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ExcelDatabaseImportTool.Models.Configuration.ImportConfiguration", "ImportConfiguration")
                        .WithMany("FieldMappings")
                        .HasForeignKey("ImportConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ForeignKeyMapping");

                    b.Navigation("ImportConfiguration");
                });

            modelBuilder.Entity("ExcelDatabaseImportTool.Models.Configuration.ImportConfiguration", b =>
                {
                    b.HasOne("ExcelDatabaseImportTool.Models.Configuration.DatabaseConfiguration", "DatabaseConfiguration")
                        .WithMany("ImportConfigurations")
                        .HasForeignKey("DatabaseConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DatabaseConfiguration");
                });

            modelBuilder.Entity("ExcelDatabaseImportTool.Models.Domain.ImportLog", b =>
                {
                    b.HasOne("ExcelDatabaseImportTool.Models.Configuration.ImportConfiguration", "ImportConfiguration")
                        .WithMany("ImportLogs")
                        .HasForeignKey("ImportConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportConfiguration");
                });

            modelBuilder.Entity("ExcelDatabaseImportTool.Models.Configuration.DatabaseConfiguration", b =>
                {
                    b.Navigation("ImportConfigurations");
                });

            modelBuilder.Entity("ExcelDatabaseImportTool.Models.Configuration.ForeignKeyMapping", b =>
                {
                    b.Navigation("FieldMappings");
                });

            modelBuilder.Entity("ExcelDatabaseImportTool.Models.Configuration.ImportConfiguration", b =>
                {
                    b.Navigation("FieldMappings");

                    b.Navigation("ImportLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
